services:
  seating-app:
    build: .
    container_name: seating_app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./input:/app/input
      - ./inputs:/app/inputs
      - ./output:/app/output
      - ./outputs:/app/outputs
      - ./photos:/app/photos
      - ./no_image_available.png:/app/no_image_available.png
      - ./app.log:/app/app.log
      - ./seating_alloc.log:/app/seating_alloc.log